require('dotenv').config();

const mongoose = require('mongoose');
const Therapist = require('../models/Therapist');
const User = require('../models/User');
const connectDB = require('./db');

const therapists = [
  {
    name: 'Dr. Sarah Chen',
    title: 'Licensed Clinical Psychologist',
    avatar: 'SC',
    avatarColor: '#E1F5EE',
    avatarTextColor: '#0F6E56',
    bio: 'Dr. Chen specializes in cognitive-behavioral therapy and mindfulness-based approaches for anxiety and depression. With 12 years of experience, she brings warmth and evidence-based techniques to every session.',
    specialties: ['Anxiety', 'Depression', 'CBT', 'Mindfulness'],
    approaches: ['Cognitive-Behavioral Therapy', 'Mindfulness-Based Stress Reduction', 'Acceptance & Commitment Therapy'],
    education: 'PhD Clinical Psychology, Stanford University',
    licenseNumber: 'PSY-CA-28471',
    yearsExperience: 12,
    rating: 4.9,
    reviewCount: 127,
    pricePerSession: 120,
    averageResponseTime: '< 1 hour',
    sessionCompletionRate: 98,
    verifiedCredentials: true,
    portalPin: '0000',
    languages: ['English', 'Mandarin'],
    availability: {
      monday: ['9:00 AM', '10:00 AM', '2:00 PM', '3:00 PM'],
      tuesday: ['10:00 AM', '11:00 AM', '4:00 PM'],
      wednesday: ['9:00 AM', '2:00 PM', '3:00 PM', '4:00 PM'],
      thursday: ['10:00 AM', '11:00 AM', '3:00 PM'],
      friday: ['9:00 AM', '10:00 AM', '2:00 PM'],
    },
    sessionTypes: ['video', 'phone', 'chat'],
    isAvailable: true,
  },
  {
    name: 'Marcus Williams, LMFT',
    title: 'Licensed Marriage & Family Therapist',
    avatar: 'MW',
    avatarColor: '#EEEDFE',
    avatarTextColor: '#534AB7',
    bio: 'Marcus helps couples and families navigate complex relationship dynamics and heal from trauma. His culturally informed approach creates a safe space for all clients.',
    specialties: ['Relationships', 'Trauma', 'Family Therapy', 'Couples Counseling'],
    approaches: ['Emotionally Focused Therapy', 'Narrative Therapy', 'Trauma-Informed Care'],
    education: 'MA Marriage & Family Therapy, USC',
    licenseNumber: 'LMFT-CA-104782',
    yearsExperience: 8,
    rating: 4.8,
    reviewCount: 89,
    pricePerSession: 100,
    averageResponseTime: '< 2 hours',
    sessionCompletionRate: 95,
    verifiedCredentials: true,
    portalPin: '0010',
    languages: ['English', 'Spanish'],
    availability: {
      monday: ['11:00 AM', '1:00 PM', '5:00 PM'],
      tuesday: ['9:00 AM', '2:00 PM', '5:00 PM'],
      wednesday: ['11:00 AM', '1:00 PM'],
      thursday: ['9:00 AM', '10:00 AM', '2:00 PM', '5:00 PM'],
      friday: ['11:00 AM', '1:00 PM', '4:00 PM'],
    },
    sessionTypes: ['video', 'phone', 'chat', 'inperson'],
    isAvailable: true,
  },
  {
    name: 'Dr. Priya Patel',
    title: 'Psychiatrist & Therapist',
    avatar: 'PP',
    avatarColor: '#FAECE7',
    avatarTextColor: '#993C1D',
    bio: 'Dr. Patel combines psychiatric expertise with deep therapeutic approaches. She specializes in trauma-informed care and EMDR, helping clients process difficult experiences and reclaim their lives.',
    specialties: ['Depression', 'Anxiety', 'Trauma', 'PTSD', 'Medication Management'],
    approaches: ['EMDR', 'Trauma-Informed CBT', 'Psychodynamic Therapy'],
    education: 'MD Psychiatry, Johns Hopkins University',
    licenseNumber: 'MD-CA-A98124',
    yearsExperience: 15,
    rating: 5.0,
    reviewCount: 203,
    pricePerSession: 150,
    averageResponseTime: '< 2 hours',
    sessionCompletionRate: 99,
    verifiedCredentials: true,
    portalPin: '0020',
    languages: ['English', 'Hindi', 'Gujarati'],
    availability: {
      monday: ['10:00 AM', '11:00 AM', '3:00 PM'],
      tuesday: ['10:00 AM', '4:00 PM', '5:00 PM'],
      wednesday: ['11:00 AM', '3:00 PM', '4:00 PM'],
      thursday: ['10:00 AM', '11:00 AM', '5:00 PM'],
      friday: ['10:00 AM', '3:00 PM'],
    },
    sessionTypes: ['video', 'phone', 'inperson'],
    isAvailable: true,
  },
  {
    name: 'James Rivera, LCSW',
    title: 'Licensed Clinical Social Worker',
    avatar: 'JR',
    avatarColor: '#FAEEDA',
    avatarTextColor: '#854F0B',
    bio: 'James uses evidence-based CBT and mindfulness techniques to help clients manage anxiety, stress, and navigate major life transitions. He believes in empowering clients with practical skills.',
    specialties: ['Anxiety', 'CBT', 'Mindfulness', 'Stress Management', 'Life Transitions'],
    approaches: ['Cognitive-Behavioral Therapy', 'Mindfulness', 'Solution-Focused Therapy'],
    education: 'MSW Clinical Social Work, UCLA',
    licenseNumber: 'LCSW-CA-87234',
    yearsExperience: 6,
    rating: 4.7,
    reviewCount: 64,
    pricePerSession: 90,
    averageResponseTime: '< 4 hours',
    sessionCompletionRate: 93,
    verifiedCredentials: true,
    portalPin: '0030',
    languages: ['English', 'Spanish'],
    availability: {
      monday: ['8:00 AM', '9:00 AM', '1:00 PM', '2:00 PM'],
      tuesday: ['8:00 AM', '2:00 PM', '3:00 PM'],
      wednesday: ['9:00 AM', '1:00 PM'],
      thursday: ['8:00 AM', '9:00 AM', '2:00 PM'],
      friday: ['8:00 AM', '1:00 PM', '2:00 PM'],
    },
    sessionTypes: ['video', 'phone', 'chat'],
    isAvailable: true,
  },
  {
    name: 'Dr. Amina Hassan',
    title: 'Clinical Psychologist',
    avatar: 'AH',
    avatarColor: '#EAF3DE',
    avatarTextColor: '#3B6D11',
    bio: 'Dr. Hassan provides compassionate care for trauma survivors and those experiencing grief and loss. Her EMDR and narrative therapy approach helps clients rewrite their stories with strength.',
    specialties: ['Trauma', 'Depression', 'Grief', 'PTSD', 'Cultural Identity'],
    approaches: ['EMDR', 'Narrative Therapy', 'Grief Counseling', 'Multicultural Counseling'],
    education: 'PhD Clinical Psychology, Columbia University',
    licenseNumber: 'PSY-CA-31902',
    yearsExperience: 10,
    rating: 4.9,
    reviewCount: 156,
    pricePerSession: 130,
    averageResponseTime: '< 1 hour',
    sessionCompletionRate: 97,
    verifiedCredentials: true,
    portalPin: '0040',
    languages: ['English', 'Arabic', 'French'],
    availability: {
      monday: ['10:00 AM', '2:00 PM', '3:00 PM'],
      tuesday: ['10:00 AM', '11:00 AM', '3:00 PM'],
      wednesday: ['10:00 AM', '2:00 PM'],
      thursday: ['11:00 AM', '2:00 PM', '3:00 PM'],
      friday: ['10:00 AM', '11:00 AM'],
    },
    sessionTypes: ['video', 'phone', 'inperson'],
    isAvailable: true,
  },
  {
    name: 'Lisa Tanaka, LPC',
    title: 'Licensed Professional Counselor',
    avatar: 'LT',
    avatarColor: '#FBEAF0',
    avatarTextColor: '#993556',
    bio: 'Lisa focuses on helping clients build self-confidence and healthier relationship patterns through CBT and acceptance-based approaches. Her warm, direct style creates a judgment-free environment.',
    specialties: ['Relationships', 'Anxiety', 'Self-esteem', 'CBT', 'Identity & Self-discovery'],
    approaches: ['CBT', 'Acceptance & Commitment Therapy', 'Interpersonal Therapy'],
    education: 'MEd Counseling, University of Washington',
    licenseNumber: 'LPC-WA-CP61843',
    yearsExperience: 7,
    rating: 4.8,
    reviewCount: 98,
    pricePerSession: 95,
    averageResponseTime: '< 4 hours',
    sessionCompletionRate: 94,
    verifiedCredentials: true,
    portalPin: '0050',
    languages: ['English', 'Japanese'],
    availability: {
      monday: ['9:00 AM', '4:00 PM', '5:00 PM', '6:00 PM'],
      tuesday: ['9:00 AM', '10:00 AM', '5:00 PM', '6:00 PM'],
      wednesday: ['4:00 PM', '5:00 PM', '6:00 PM'],
      thursday: ['9:00 AM', '10:00 AM', '4:00 PM'],
      friday: ['9:00 AM', '5:00 PM', '6:00 PM'],
    },
    sessionTypes: ['video', 'phone', 'chat', 'inperson'],
    isAvailable: true,
  },
  {
    name: 'Dr. Elena Vasquez',
    title: 'Clinical Psychologist',
    avatar: 'EV',
    avatarColor: '#E3F0FB',
    avatarTextColor: '#1D5A8C',
    bio: 'Dr. Vasquez helps clients navigate grief, loss, and major life transitions with a gentle, person-centered approach. She believes healing happens at its own pace, and meets every client where they are.',
    specialties: ['Grief', 'Life Transitions', 'Depression', 'Self-esteem'],
    approaches: ['Person-Centered Therapy', 'Grief Counseling', 'Existential Therapy'],
    education: 'PsyD Clinical Psychology, University of Denver',
    licenseNumber: 'PSY-CO-19284',
    yearsExperience: 11,
    rating: 4.9,
    reviewCount: 142,
    pricePerSession: 115,
    averageResponseTime: '< 2 hours',
    sessionCompletionRate: 96,
    verifiedCredentials: true,
    portalPin: '0060',
    languages: ['English', 'Spanish'],
    availability: {
      monday: ['9:00 AM', '11:00 AM', '2:00 PM'],
      tuesday: ['9:00 AM', '1:00 PM', '3:00 PM'],
      wednesday: ['10:00 AM', '2:00 PM', '4:00 PM'],
      thursday: ['9:00 AM', '11:00 AM'],
      friday: ['10:00 AM', '2:00 PM', '3:00 PM'],
    },
    sessionTypes: ['video', 'phone', 'chat'],
    isAvailable: true,
  },
  {
    name: 'David Okafor, LMHC',
    title: 'Licensed Mental Health Counselor',
    avatar: 'DO',
    avatarColor: '#FDEDE3',
    avatarTextColor: '#B14B12',
    bio: 'David specializes in stress management and burnout recovery for high-pressure careers. He combines mindfulness practices with practical, structured coaching to help clients regain balance.',
    specialties: ['Stress Management', 'Anxiety', 'Life Transitions', 'Mindfulness'],
    approaches: ['Mindfulness-Based Stress Reduction', 'Solution-Focused Therapy', 'CBT'],
    education: 'MA Clinical Mental Health Counseling, NYU',
    licenseNumber: 'LMHC-NY-47210',
    yearsExperience: 9,
    rating: 4.7,
    reviewCount: 111,
    pricePerSession: 105,
    averageResponseTime: '< 24 hours',
    sessionCompletionRate: 91,
    verifiedCredentials: true,
    portalPin: '0070',
    languages: ['English', 'Igbo'],
    availability: {
      monday: ['7:00 AM', '8:00 AM', '12:00 PM'],
      tuesday: ['7:00 AM', '12:00 PM', '6:00 PM'],
      wednesday: ['8:00 AM', '12:00 PM', '6:00 PM'],
      thursday: ['7:00 AM', '8:00 AM', '6:00 PM'],
      friday: ['7:00 AM', '12:00 PM'],
    },
    sessionTypes: ['video', 'phone', 'chat'],
    isAvailable: true,
  },
  {
    name: 'Dr. Grace Kim',
    title: 'Licensed Clinical Psychologist',
    avatar: 'GK',
    avatarColor: '#F1E9FB',
    avatarTextColor: '#6B3FA0',
    bio: 'Dr. Kim works with individuals and couples navigating trust, communication breakdowns, and cultural identity within relationships. She creates a calm, structured space for hard conversations.',
    specialties: ['Relationships', 'Couples Counseling', 'Cultural Identity', 'Family Therapy'],
    approaches: ['Emotionally Focused Therapy', 'Gottman Method', 'Multicultural Counseling'],
    education: 'PhD Clinical Psychology, University of Michigan',
    licenseNumber: 'PSY-MI-33012',
    yearsExperience: 13,
    rating: 4.9,
    reviewCount: 178,
    pricePerSession: 125,
    averageResponseTime: '< 1 hour',
    sessionCompletionRate: 98,
    verifiedCredentials: true,
    portalPin: '0080',
    languages: ['English', 'Korean'],
    availability: {
      monday: ['10:00 AM', '1:00 PM', '4:00 PM'],
      tuesday: ['10:00 AM', '2:00 PM'],
      wednesday: ['1:00 PM', '4:00 PM', '5:00 PM'],
      thursday: ['10:00 AM', '2:00 PM', '4:00 PM'],
      friday: ['10:00 AM', '1:00 PM'],
    },
    sessionTypes: ['video', 'inperson'],
    isAvailable: true,
  },
  {
    name: 'Michael Brennan, LCSW',
    title: 'Licensed Clinical Social Worker',
    avatar: 'MB',
    avatarColor: '#E6F4EF',
    avatarTextColor: '#1B7A56',
    bio: 'Michael has spent over a decade supporting veterans and first responders through trauma and PTSD recovery. His grounded, no-nonsense style builds trust quickly.',
    specialties: ['PTSD', 'Trauma', 'Anxiety', 'Medication Management'],
    approaches: ['Trauma-Informed CBT', 'EMDR', 'Prolonged Exposure Therapy'],
    education: 'MSW Clinical Social Work, University of Texas',
    licenseNumber: 'LCSW-TX-58821',
    yearsExperience: 14,
    rating: 4.8,
    reviewCount: 165,
    pricePerSession: 110,
    averageResponseTime: '< 4 hours',
    sessionCompletionRate: 95,
    verifiedCredentials: true,
    portalPin: '0090',
    languages: ['English'],
    availability: {
      monday: ['8:00 AM', '9:00 AM', '3:00 PM'],
      tuesday: ['8:00 AM', '3:00 PM', '4:00 PM'],
      wednesday: ['9:00 AM', '3:00 PM'],
      thursday: ['8:00 AM', '9:00 AM', '4:00 PM'],
      friday: ['8:00 AM', '3:00 PM', '4:00 PM'],
    },
    sessionTypes: ['video', 'phone', 'inperson'],
    isAvailable: true,
  },
  {
    name: 'Dr. Naomi Osei',
    title: 'Clinical Psychologist',
    avatar: 'NO',
    avatarColor: '#FDEEDB',
    avatarTextColor: '#9C5B0A',
    bio: 'Dr. Osei helps clients build a stronger sense of self-worth and navigate identity questions with warmth and curiosity. She draws on narrative and strengths-based approaches.',
    specialties: ['Self-esteem', 'Identity & Self-discovery', 'Depression', 'Anxiety'],
    approaches: ['Narrative Therapy', 'Strengths-Based Therapy', 'CBT'],
    education: 'PhD Clinical Psychology, Howard University',
    licenseNumber: 'PSY-DC-22156',
    yearsExperience: 8,
    rating: 4.9,
    reviewCount: 134,
    pricePerSession: 100,
    averageResponseTime: '< 2 hours',
    sessionCompletionRate: 97,
    verifiedCredentials: true,
    portalPin: '0100',
    languages: ['English', 'Twi'],
    availability: {
      monday: ['11:00 AM', '3:00 PM', '5:00 PM'],
      tuesday: ['11:00 AM', '1:00 PM', '5:00 PM'],
      wednesday: ['11:00 AM', '3:00 PM'],
      thursday: ['1:00 PM', '3:00 PM', '5:00 PM'],
      friday: ['11:00 AM', '1:00 PM'],
    },
    sessionTypes: ['video', 'phone', 'chat'],
    isAvailable: true,
  },
  {
    name: 'Thomas Reilly, LPC',
    title: 'Licensed Professional Counselor',
    avatar: 'TR',
    avatarColor: '#EDF6E8',
    avatarTextColor: '#3F7A1E',
    bio: 'Thomas works with individuals experiencing sleep difficulties, chronic stress, and burnout. He takes a practical, habit-focused approach rooted in CBT-I and stress physiology.',
    specialties: ['Stress Management', 'CBT', 'Mindfulness', 'Life Transitions'],
    approaches: ['CBT for Insomnia', 'Mindfulness', 'Behavioral Activation'],
    education: 'MEd Counseling, Penn State University',
    licenseNumber: 'LPC-PA-39104',
    yearsExperience: 6,
    rating: 4.6,
    reviewCount: 72,
    pricePerSession: 85,
    averageResponseTime: '< 24 hours',
    sessionCompletionRate: 89,
    verifiedCredentials: true,
    portalPin: '0110',
    languages: ['English'],
    availability: {
      monday: ['6:00 PM', '7:00 PM'],
      tuesday: ['6:00 PM', '7:00 PM', '8:00 PM'],
      wednesday: ['6:00 PM', '7:00 PM'],
      thursday: ['6:00 PM', '7:00 PM', '8:00 PM'],
      friday: ['5:00 PM', '6:00 PM'],
    },
    sessionTypes: ['video', 'chat'],
    isAvailable: true,
  },
  {
    name: 'Dr. Fatima Al-Sayed',
    title: 'Psychiatrist & Therapist',
    avatar: 'FA',
    avatarColor: '#F3E8F1',
    avatarTextColor: '#8A2F73',
    bio: 'Dr. Al-Sayed integrates medication management with talk therapy for clients managing depression, anxiety, and complex trauma histories. She takes a holistic, whole-person approach to care.',
    specialties: ['Depression', 'Anxiety', 'Medication Management', 'Trauma'],
    approaches: ['Psychodynamic Therapy', 'Trauma-Informed CBT', 'Medication Management'],
    education: 'MD Psychiatry, University of Chicago',
    licenseNumber: 'MD-IL-B71029',
    yearsExperience: 16,
    rating: 5.0,
    reviewCount: 221,
    pricePerSession: 160,
    averageResponseTime: '< 1 hour',
    sessionCompletionRate: 99,
    verifiedCredentials: true,
    portalPin: '0120',
    languages: ['English', 'Arabic'],
    availability: {
      monday: ['9:00 AM', '10:00 AM', '1:00 PM'],
      tuesday: ['9:00 AM', '1:00 PM', '2:00 PM'],
      wednesday: ['10:00 AM', '1:00 PM'],
      thursday: ['9:00 AM', '10:00 AM', '2:00 PM'],
      friday: ['9:00 AM', '1:00 PM'],
    },
    sessionTypes: ['video', 'phone', 'inperson'],
    isAvailable: true,
  },
  {
    name: 'Ben Coleman, LMFT',
    title: 'Licensed Marriage & Family Therapist',
    avatar: 'BC',
    avatarColor: '#E7F1FA',
    avatarTextColor: '#245A85',
    bio: 'Ben supports families and young adults through major life transitions — new jobs, moves, breakups, and everything in between. His approachable style makes hard conversations feel manageable.',
    specialties: ['Life Transitions', 'Family Therapy', 'Relationships', 'Self-esteem'],
    approaches: ['Solution-Focused Therapy', 'Narrative Therapy', 'Family Systems Therapy'],
    education: 'MA Marriage & Family Therapy, Pepperdine University',
    licenseNumber: 'LMFT-CA-77451',
    yearsExperience: 5,
    rating: 4.7,
    reviewCount: 58,
    pricePerSession: 90,
    averageResponseTime: '< 4 hours',
    sessionCompletionRate: 92,
    verifiedCredentials: true,
    portalPin: '0130',
    languages: ['English'],
    availability: {
      monday: ['1:00 PM', '2:00 PM', '6:00 PM'],
      tuesday: ['1:00 PM', '6:00 PM', '7:00 PM'],
      wednesday: ['2:00 PM', '6:00 PM'],
      thursday: ['1:00 PM', '2:00 PM', '7:00 PM'],
      friday: ['1:00 PM', '6:00 PM'],
    },
    sessionTypes: ['video', 'phone', 'chat', 'inperson'],
    isAvailable: true,
  },
];

const seedDB = async () => {
  await connectDB();
  try {
    await Therapist.deleteMany({});
    await Therapist.insertMany(therapists);
    console.log(`Seeded ${therapists.length} therapists`);

    await User.deleteOne({ email: 'demo@healthify.com' });
    await User.create({
      name: 'Demo User',
      email: 'demo@healthify.com',
      password: 'demo1234',
    });
    console.log('Created demo user: demo@healthify.com / demo1234');

    process.exit(0);
  } catch (err) {
    console.error('Seed error:', err);
    process.exit(1);
  }
};

seedDB();
  